// src/components/SummaryCard.jsx
// Displays summary as clean bullet points, keywords, and export button

import jsPDF from 'jspdf'

// ── Helper: split summary text into bullet points ─────────────────────────────
// Splits on sentence boundaries (. ! ?) and filters out empty strings
function splitIntoBullets(text) {
  if (!text) return []
  // Split on period/exclamation/question mark followed by a space or end
  const sentences = text.match(/[^.!?]+[.!?]+/g) || [text]
  return sentences
    .map(s => s.trim())
    .filter(s => s.length > 10) // ignore very short fragments
}

export default function SummaryCard({ summary, keywords, error, isLoading }) {

  const bullets = splitIntoBullets(summary)

  // ── Export as PDF ─────────────────────────────────────────────────────────
  const handleExportPDF = () => {
    const doc = new jsPDF()
    const margin = 20
    const pageWidth = doc.internal.pageSize.getWidth()
    const maxWidth = pageWidth - margin * 2
    let y = margin

    // Title
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(18)
    doc.setTextColor(40, 40, 40)
    doc.text('AI Text Summarizer', margin, y)
    y += 8

    // Amber accent line
    doc.setDrawColor(251, 191, 36)
    doc.setLineWidth(1)
    doc.line(margin, y, margin + 40, y)
    y += 10

    // Timestamp
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(150, 150, 150)
    doc.text(`Generated on ${new Date().toLocaleString()}`, margin, y)
    y += 12

    // Summary heading
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(40, 40, 40)
    doc.text('Summary', margin, y)
    y += 7

    // Bullet points
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(60, 60, 60)
    bullets.forEach((bullet) => {
      const lines = doc.splitTextToSize(`• ${bullet}`, maxWidth - 4)
      // Add new page if running out of space
      if (y + lines.length * 6 > 270) {
        doc.addPage()
        y = margin
      }
      doc.text(lines, margin, y)
      y += lines.length * 6 + 3
    })
    y += 6

    // Keywords
    if (keywords && keywords.length > 0) {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(12)
      doc.setTextColor(40, 40, 40)
      doc.text('Keywords', margin, y)
      y += 7
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(10)
      doc.setTextColor(80, 80, 80)
      doc.text(keywords.join('  •  '), margin, y)
    }

    doc.save('summary.pdf')
  }

  if (!isLoading && !summary && !error) return null

  return (
    <div className="flex flex-col gap-4">

      {/* ── SUMMARY CARD ──────────────────────────────────────────────────── */}
      <div>
        <label className="text-sm font-medium text-stone-600 tracking-wide uppercase">
          Summary
        </label>

        <div className="mt-2 rounded-xl border border-stone-200 bg-white shadow-sm overflow-hidden">

          {/* Loading */}
          {isLoading && (
            <div className="flex items-center gap-3 px-5 py-6 text-stone-400">
              <div className="h-5 w-5 rounded-full border-2 border-amber-400 border-t-transparent animate-spin" />
              <span className="text-sm">Generating summary, please wait...</span>
            </div>
          )}

          {/* Error */}
          {!isLoading && error && (
            <div className="flex items-start gap-3 px-5 py-5 bg-red-50 border border-red-100 rounded-xl">
              <span className="text-red-400 text-lg mt-0.5">⚠️</span>
              <div>
                <p className="text-sm font-semibold text-red-600">Something went wrong</p>
                <p className="text-sm text-red-500 mt-0.5">{error}</p>
              </div>
            </div>
          )}

          {/* Success — bullet point list */}
          {!isLoading && summary && (
            <div className="px-5 py-5">

              {/* Bullet points */}
              <ul className="flex flex-col gap-2">
                {bullets.map((point, index) => (
                  <li key={index} className="flex items-start gap-3">
                    {/* Bullet dot */}
                    <span className="mt-1.5 h-2 w-2 flex-shrink-0 rounded-full bg-amber-400" />
                    {/* Sentence text */}
                    <p className="text-stone-700 text-sm leading-relaxed">{point}</p>
                  </li>
                ))}
              </ul>

              <p className="mt-4 text-xs text-stone-300 border-t border-stone-100 pt-3">
                Generated by your FastAPI + HuggingFace backend
              </p>
            </div>
          )}

        </div>
      </div>

      {/* ── KEYWORDS ──────────────────────────────────────────────────────── */}
      {!isLoading && keywords && keywords.length > 0 && (
        <div>
          <label className="text-sm font-medium text-stone-600 tracking-wide uppercase">
            Keywords
          </label>
          <div className="mt-2 flex flex-wrap gap-2">
            {keywords.map((kw, index) => (
              <span
                key={index}
                className="px-3 py-1 rounded-full bg-amber-50 border border-amber-200 text-amber-800 text-xs font-medium"
              >
                {kw}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* No keywords fallback */}
      {!isLoading && summary && (!keywords || keywords.length === 0) && (
        <p className="text-xs text-stone-300">No keywords detected.</p>
      )}

      {/* ── EXPORT BUTTON ─────────────────────────────────────────────────── */}
      {!isLoading && summary && (
        <div className="flex justify-end">
          <button
            onClick={handleExportPDF}
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl border border-stone-200 bg-white text-stone-600 text-sm font-medium hover:bg-stone-50 hover:border-stone-300 active:scale-95 transition-all duration-200 shadow-sm"
          >
            <span>⬇</span> Download Summary as PDF
          </button>
        </div>
      )}

    </div>
  )
}
